import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    /*
      Build output and generated files.

      `.vercel` and `.tanstack` were missing, and `.vercel/output` holds the
      entire built client bundle — so `eslint .` was linting every emitted asset
      and took minutes rather than seconds. A lint run nobody can afford to wait
      for is a lint run nobody does, which is how the repo ended up with no CI
      lint gate at all.

      routeTree.gen.ts is regenerated by the router plugin on every build; there
      is nothing to fix in it by hand.
    */
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      ".vercel",
      ".tanstack",
      ".wrangler",
      ".lovable",
      "scraper-service",
      "src/routeTree.gen.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      /*
        Was "off" entirely, which is why ~2,000 lines of unused shadcn primitives
        and several dead exports never surfaced. Set to "warn" rather than
        "error" deliberately: it makes the dead code visible without turning CI
        red on a backlog that predates the gate. Raise to "error" once the
        existing warnings are cleared.
      */
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  eslintPluginPrettier,
);
