/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as AuthenticatedClassroomsRouteImport } from './routes/_authenticated.classrooms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated.overview'
import { Route as StudentsRollRouteImport } from './routes/students.$roll'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated._admin.import'
import { Route as AuthenticatedAdminScrapeRunsRouteImport } from './routes/_authenticated._admin.scrape-runs'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated._admin.settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated._admin.staff'
import { Route as AuthenticatedClassroomsIndexRouteImport } from './routes/_authenticated.classrooms.index'
import { Route as AuthenticatedClassroomsIdRouteImport } from './routes/_authenticated.classrooms.$id'
import { Route as AuthenticatedAdminClassroomsNewRouteImport } from './routes/_authenticated._admin.classrooms.new'
import { Route as ApiPublicCronRefreshRouteImport } from './routes/api/public/cron/refresh'
import { Route as AuthenticatedClassroomsIdStudentsNewRouteImport } from './routes/_authenticated.classrooms.$id.students.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassroomsRoute = AuthenticatedClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StudentsRollRoute = StudentsRollRouteImport.update({
  id: '/students/$roll',
  path: '/students/$roll',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScrapeRunsRoute =
  AuthenticatedAdminScrapeRunsRouteImport.update({
    id: '/scrape-runs',
    path: '/scrape-runs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedClassroomsIndexRoute =
  AuthenticatedClassroomsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)
const AuthenticatedClassroomsIdRoute =
  AuthenticatedClassroomsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)
const AuthenticatedAdminClassroomsNewRoute =
  AuthenticatedAdminClassroomsNewRouteImport.update({
    id: '/classrooms/new',
    path: '/classrooms/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronRefreshRoute = ApiPublicCronRefreshRouteImport.update({
  id: '/api/public/cron/refresh',
  path: '/api/public/cron/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassroomsIdStudentsNewRoute =
  AuthenticatedClassroomsIdStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedClassroomsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classrooms': typeof AuthenticatedClassroomsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/students/$roll': typeof StudentsRollRoute
  '/import': typeof AuthenticatedAdminImportRoute
  '/scrape-runs': typeof AuthenticatedAdminScrapeRunsRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff': typeof AuthenticatedAdminStaffRoute
  '/classrooms/$id': typeof AuthenticatedClassroomsIdRouteWithChildren
  '/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/classrooms/new': typeof AuthenticatedAdminClassroomsNewRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/classrooms/$id/students/new': typeof AuthenticatedClassroomsIdStudentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/students/$roll': typeof StudentsRollRoute
  '/import': typeof AuthenticatedAdminImportRoute
  '/scrape-runs': typeof AuthenticatedAdminScrapeRunsRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff': typeof AuthenticatedAdminStaffRoute
  '/classrooms/$id': typeof AuthenticatedClassroomsIdRouteWithChildren
  '/classrooms': typeof AuthenticatedClassroomsIndexRoute
  '/classrooms/new': typeof AuthenticatedAdminClassroomsNewRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/classrooms/$id/students/new': typeof AuthenticatedClassroomsIdStudentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/classrooms': typeof AuthenticatedClassroomsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/students/$roll': typeof StudentsRollRoute
  '/_authenticated/_admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/_admin/scrape-runs': typeof AuthenticatedAdminScrapeRunsRoute
  '/_authenticated/_admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/_admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/classrooms/$id': typeof AuthenticatedClassroomsIdRouteWithChildren
  '/_authenticated/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/_authenticated/_admin/classrooms/new': typeof AuthenticatedAdminClassroomsNewRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/_authenticated/classrooms/$id/students/new': typeof AuthenticatedClassroomsIdStudentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classrooms'
    | '/dashboard'
    | '/overview'
    | '/students/$roll'
    | '/import'
    | '/scrape-runs'
    | '/settings'
    | '/staff'
    | '/classrooms/$id'
    | '/classrooms/'
    | '/classrooms/new'
    | '/api/public/cron/refresh'
    | '/classrooms/$id/students/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/overview'
    | '/students/$roll'
    | '/import'
    | '/scrape-runs'
    | '/settings'
    | '/staff'
    | '/classrooms/$id'
    | '/classrooms'
    | '/classrooms/new'
    | '/api/public/cron/refresh'
    | '/classrooms/$id/students/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/classrooms'
    | '/_authenticated/dashboard'
    | '/_authenticated/overview'
    | '/students/$roll'
    | '/_authenticated/_admin/import'
    | '/_authenticated/_admin/scrape-runs'
    | '/_authenticated/_admin/settings'
    | '/_authenticated/_admin/staff'
    | '/_authenticated/classrooms/$id'
    | '/_authenticated/classrooms/'
    | '/_authenticated/_admin/classrooms/new'
    | '/api/public/cron/refresh'
    | '/_authenticated/classrooms/$id/students/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  StudentsRollRoute: typeof StudentsRollRoute
  ApiPublicCronRefreshRoute: typeof ApiPublicCronRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classrooms': {
      id: '/_authenticated/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof AuthenticatedClassroomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/students/$roll': {
      id: '/students/$roll'
      path: '/students/$roll'
      fullPath: '/students/$roll'
      preLoaderRoute: typeof StudentsRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/import': {
      id: '/_authenticated/_admin/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/scrape-runs': {
      id: '/_authenticated/_admin/scrape-runs'
      path: '/scrape-runs'
      fullPath: '/scrape-runs'
      preLoaderRoute: typeof AuthenticatedAdminScrapeRunsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/settings': {
      id: '/_authenticated/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/staff': {
      id: '/_authenticated/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/classrooms/': {
      id: '/_authenticated/classrooms/'
      path: '/'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof AuthenticatedClassroomsIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
    '/_authenticated/classrooms/$id': {
      id: '/_authenticated/classrooms/$id'
      path: '/$id'
      fullPath: '/classrooms/$id'
      preLoaderRoute: typeof AuthenticatedClassroomsIdRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
    '/_authenticated/_admin/classrooms/new': {
      id: '/_authenticated/_admin/classrooms/new'
      path: '/classrooms/new'
      fullPath: '/classrooms/new'
      preLoaderRoute: typeof AuthenticatedAdminClassroomsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/refresh': {
      id: '/api/public/cron/refresh'
      path: '/api/public/cron/refresh'
      fullPath: '/api/public/cron/refresh'
      preLoaderRoute: typeof ApiPublicCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classrooms/$id/students/new': {
      id: '/_authenticated/classrooms/$id/students/new'
      path: '/students/new'
      fullPath: '/classrooms/$id/students/new'
      preLoaderRoute: typeof AuthenticatedClassroomsIdStudentsNewRouteImport
      parentRoute: typeof AuthenticatedClassroomsIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminScrapeRunsRoute: typeof AuthenticatedAdminScrapeRunsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminClassroomsNewRoute: typeof AuthenticatedAdminClassroomsNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminScrapeRunsRoute: AuthenticatedAdminScrapeRunsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminClassroomsNewRoute: AuthenticatedAdminClassroomsNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClassroomsIdRouteChildren {
  AuthenticatedClassroomsIdStudentsNewRoute: typeof AuthenticatedClassroomsIdStudentsNewRoute
}

const AuthenticatedClassroomsIdRouteChildren: AuthenticatedClassroomsIdRouteChildren =
  {
    AuthenticatedClassroomsIdStudentsNewRoute:
      AuthenticatedClassroomsIdStudentsNewRoute,
  }

const AuthenticatedClassroomsIdRouteWithChildren =
  AuthenticatedClassroomsIdRoute._addFileChildren(
    AuthenticatedClassroomsIdRouteChildren,
  )

interface AuthenticatedClassroomsRouteChildren {
  AuthenticatedClassroomsIdRoute: typeof AuthenticatedClassroomsIdRouteWithChildren
  AuthenticatedClassroomsIndexRoute: typeof AuthenticatedClassroomsIndexRoute
}

const AuthenticatedClassroomsRouteChildren: AuthenticatedClassroomsRouteChildren =
  {
    AuthenticatedClassroomsIdRoute: AuthenticatedClassroomsIdRouteWithChildren,
    AuthenticatedClassroomsIndexRoute: AuthenticatedClassroomsIndexRoute,
  }

const AuthenticatedClassroomsRouteWithChildren =
  AuthenticatedClassroomsRoute._addFileChildren(
    AuthenticatedClassroomsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClassroomsRoute: typeof AuthenticatedClassroomsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClassroomsRoute: AuthenticatedClassroomsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  StudentsRollRoute: StudentsRollRoute,
  ApiPublicCronRefreshRoute: ApiPublicCronRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
