/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as AuthenticatedClassroomsRouteImport } from './routes/_authenticated.classrooms'
import { Route as AuthenticatedCollegesRouteImport } from './routes/_authenticated.colleges'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated.overview'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated.rankings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as StudentsRollRouteImport } from './routes/students.$roll'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated._admin.import'
import { Route as AuthenticatedAdminPlatformsRouteImport } from './routes/_authenticated._admin.platforms'
import { Route as AuthenticatedAdminScrapeRunsRouteImport } from './routes/_authenticated._admin.scrape-runs'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated._admin.settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated._admin.staff'
import { Route as AuthenticatedClassroomsIndexRouteImport } from './routes/_authenticated.classrooms.index'
import { Route as AuthenticatedClassroomsIdRouteImport } from './routes/_authenticated.classrooms.$id'
import { Route as AuthenticatedAdminClassroomsNewRouteImport } from './routes/_authenticated._admin.classrooms.new'
import { Route as ApiPublicCronRefreshRouteImport } from './routes/api/public/cron/refresh'
import { Route as ApiPublicCronSeedDemoRouteImport } from './routes/api/public/cron/seed-demo'
import { Route as ApiPublicJobsPumpRouteImport } from './routes/api/public/jobs/pump'
import { Route as ApiPublicJobsRunRouteImport } from './routes/api/public/jobs/run'
import { Route as AuthenticatedClassroomsIdStudentsNewRouteImport } from './routes/_authenticated.classrooms.$id_.students.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassroomsRoute = AuthenticatedClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollegesRoute = AuthenticatedCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StudentsRollRoute = StudentsRollRouteImport.update({
  id: '/students/$roll',
  path: '/students/$roll',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformsRoute =
  AuthenticatedAdminPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminScrapeRunsRoute =
  AuthenticatedAdminScrapeRunsRouteImport.update({
    id: '/scrape-runs',
    path: '/scrape-runs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedClassroomsIndexRoute =
  AuthenticatedClassroomsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)
const AuthenticatedClassroomsIdRoute =
  AuthenticatedClassroomsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)
const AuthenticatedAdminClassroomsNewRoute =
  AuthenticatedAdminClassroomsNewRouteImport.update({
    id: '/classrooms/new',
    path: '/classrooms/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronRefreshRoute = ApiPublicCronRefreshRouteImport.update({
  id: '/api/public/cron/refresh',
  path: '/api/public/cron/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSeedDemoRoute = ApiPublicCronSeedDemoRouteImport.update({
  id: '/api/public/cron/seed-demo',
  path: '/api/public/cron/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsPumpRoute = ApiPublicJobsPumpRouteImport.update({
  id: '/api/public/jobs/pump',
  path: '/api/public/jobs/pump',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRunRoute = ApiPublicJobsRunRouteImport.update({
  id: '/api/public/jobs/run',
  path: '/api/public/jobs/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassroomsIdStudentsNewRoute =
  AuthenticatedClassroomsIdStudentsNewRouteImport.update({
    id: '/$id_/students/new',
    path: '/$id/students/new',
    getParentRoute: () => AuthenticatedClassroomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/classrooms': typeof AuthenticatedClassroomsRouteWithChildren
  '/colleges': typeof AuthenticatedCollegesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/students/$roll': typeof StudentsRollRoute
  '/import': typeof AuthenticatedAdminImportRoute
  '/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/scrape-runs': typeof AuthenticatedAdminScrapeRunsRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff': typeof AuthenticatedAdminStaffRoute
  '/classrooms/$id': typeof AuthenticatedClassroomsIdRoute
  '/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/classrooms/new': typeof AuthenticatedAdminClassroomsNewRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/api/public/cron/seed-demo': typeof ApiPublicCronSeedDemoRoute
  '/api/public/jobs/pump': typeof ApiPublicJobsPumpRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/classrooms/$id/students/new': typeof AuthenticatedClassroomsIdStudentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/students/$roll': typeof StudentsRollRoute
  '/import': typeof AuthenticatedAdminImportRoute
  '/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/scrape-runs': typeof AuthenticatedAdminScrapeRunsRoute
  '/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff': typeof AuthenticatedAdminStaffRoute
  '/classrooms/$id': typeof AuthenticatedClassroomsIdRoute
  '/classrooms': typeof AuthenticatedClassroomsIndexRoute
  '/classrooms/new': typeof AuthenticatedAdminClassroomsNewRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/api/public/cron/seed-demo': typeof ApiPublicCronSeedDemoRoute
  '/api/public/jobs/pump': typeof ApiPublicJobsPumpRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/classrooms/$id/students/new': typeof AuthenticatedClassroomsIdStudentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/classrooms': typeof AuthenticatedClassroomsRouteWithChildren
  '/_authenticated/colleges': typeof AuthenticatedCollegesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/students/$roll': typeof StudentsRollRoute
  '/_authenticated/_admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/_admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/_authenticated/_admin/scrape-runs': typeof AuthenticatedAdminScrapeRunsRoute
  '/_authenticated/_admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/_admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/classrooms/$id': typeof AuthenticatedClassroomsIdRoute
  '/_authenticated/classrooms/': typeof AuthenticatedClassroomsIndexRoute
  '/_authenticated/_admin/classrooms/new': typeof AuthenticatedAdminClassroomsNewRoute
  '/api/public/cron/refresh': typeof ApiPublicCronRefreshRoute
  '/api/public/cron/seed-demo': typeof ApiPublicCronSeedDemoRoute
  '/api/public/jobs/pump': typeof ApiPublicJobsPumpRoute
  '/api/public/jobs/run': typeof ApiPublicJobsRunRoute
  '/_authenticated/classrooms/$id_/students/new': typeof AuthenticatedClassroomsIdStudentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/classrooms'
    | '/colleges'
    | '/dashboard'
    | '/overview'
    | '/rankings'
    | '/reports'
    | '/students/$roll'
    | '/import'
    | '/platforms'
    | '/scrape-runs'
    | '/settings'
    | '/staff'
    | '/classrooms/$id'
    | '/classrooms/'
    | '/classrooms/new'
    | '/api/public/cron/refresh'
    | '/api/public/cron/seed-demo'
    | '/api/public/jobs/pump'
    | '/api/public/jobs/run'
    | '/classrooms/$id/students/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/colleges'
    | '/dashboard'
    | '/overview'
    | '/rankings'
    | '/reports'
    | '/students/$roll'
    | '/import'
    | '/platforms'
    | '/scrape-runs'
    | '/settings'
    | '/staff'
    | '/classrooms/$id'
    | '/classrooms'
    | '/classrooms/new'
    | '/api/public/cron/refresh'
    | '/api/public/cron/seed-demo'
    | '/api/public/jobs/pump'
    | '/api/public/jobs/run'
    | '/classrooms/$id/students/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/_admin'
    | '/_authenticated/classrooms'
    | '/_authenticated/colleges'
    | '/_authenticated/dashboard'
    | '/_authenticated/overview'
    | '/_authenticated/rankings'
    | '/_authenticated/reports'
    | '/students/$roll'
    | '/_authenticated/_admin/import'
    | '/_authenticated/_admin/platforms'
    | '/_authenticated/_admin/scrape-runs'
    | '/_authenticated/_admin/settings'
    | '/_authenticated/_admin/staff'
    | '/_authenticated/classrooms/$id'
    | '/_authenticated/classrooms/'
    | '/_authenticated/_admin/classrooms/new'
    | '/api/public/cron/refresh'
    | '/api/public/cron/seed-demo'
    | '/api/public/jobs/pump'
    | '/api/public/jobs/run'
    | '/_authenticated/classrooms/$id_/students/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  StudentsRollRoute: typeof StudentsRollRoute
  ApiPublicCronRefreshRoute: typeof ApiPublicCronRefreshRoute
  ApiPublicCronSeedDemoRoute: typeof ApiPublicCronSeedDemoRoute
  ApiPublicJobsPumpRoute: typeof ApiPublicJobsPumpRoute
  ApiPublicJobsRunRoute: typeof ApiPublicJobsRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classrooms': {
      id: '/_authenticated/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof AuthenticatedClassroomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colleges': {
      id: '/_authenticated/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof AuthenticatedCollegesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/students/$roll': {
      id: '/students/$roll'
      path: '/students/$roll'
      fullPath: '/students/$roll'
      preLoaderRoute: typeof StudentsRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/import': {
      id: '/_authenticated/_admin/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/platforms': {
      id: '/_authenticated/_admin/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AuthenticatedAdminPlatformsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/scrape-runs': {
      id: '/_authenticated/_admin/scrape-runs'
      path: '/scrape-runs'
      fullPath: '/scrape-runs'
      preLoaderRoute: typeof AuthenticatedAdminScrapeRunsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/settings': {
      id: '/_authenticated/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/staff': {
      id: '/_authenticated/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/classrooms/': {
      id: '/_authenticated/classrooms/'
      path: '/'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof AuthenticatedClassroomsIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
    '/_authenticated/classrooms/$id': {
      id: '/_authenticated/classrooms/$id'
      path: '/$id'
      fullPath: '/classrooms/$id'
      preLoaderRoute: typeof AuthenticatedClassroomsIdRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
    '/_authenticated/_admin/classrooms/new': {
      id: '/_authenticated/_admin/classrooms/new'
      path: '/classrooms/new'
      fullPath: '/classrooms/new'
      preLoaderRoute: typeof AuthenticatedAdminClassroomsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/refresh': {
      id: '/api/public/cron/refresh'
      path: '/api/public/cron/refresh'
      fullPath: '/api/public/cron/refresh'
      preLoaderRoute: typeof ApiPublicCronRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/seed-demo': {
      id: '/api/public/cron/seed-demo'
      path: '/api/public/cron/seed-demo'
      fullPath: '/api/public/cron/seed-demo'
      preLoaderRoute: typeof ApiPublicCronSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/pump': {
      id: '/api/public/jobs/pump'
      path: '/api/public/jobs/pump'
      fullPath: '/api/public/jobs/pump'
      preLoaderRoute: typeof ApiPublicJobsPumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/run': {
      id: '/api/public/jobs/run'
      path: '/api/public/jobs/run'
      fullPath: '/api/public/jobs/run'
      preLoaderRoute: typeof ApiPublicJobsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classrooms/$id_/students/new': {
      id: '/_authenticated/classrooms/$id_/students/new'
      path: '/$id/students/new'
      fullPath: '/classrooms/$id/students/new'
      preLoaderRoute: typeof AuthenticatedClassroomsIdStudentsNewRouteImport
      parentRoute: typeof AuthenticatedClassroomsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminPlatformsRoute: typeof AuthenticatedAdminPlatformsRoute
  AuthenticatedAdminScrapeRunsRoute: typeof AuthenticatedAdminScrapeRunsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminClassroomsNewRoute: typeof AuthenticatedAdminClassroomsNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminPlatformsRoute: AuthenticatedAdminPlatformsRoute,
  AuthenticatedAdminScrapeRunsRoute: AuthenticatedAdminScrapeRunsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminClassroomsNewRoute: AuthenticatedAdminClassroomsNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClassroomsRouteChildren {
  AuthenticatedClassroomsIdRoute: typeof AuthenticatedClassroomsIdRoute
  AuthenticatedClassroomsIndexRoute: typeof AuthenticatedClassroomsIndexRoute
  AuthenticatedClassroomsIdStudentsNewRoute: typeof AuthenticatedClassroomsIdStudentsNewRoute
}

const AuthenticatedClassroomsRouteChildren: AuthenticatedClassroomsRouteChildren =
  {
    AuthenticatedClassroomsIdRoute: AuthenticatedClassroomsIdRoute,
    AuthenticatedClassroomsIndexRoute: AuthenticatedClassroomsIndexRoute,
    AuthenticatedClassroomsIdStudentsNewRoute:
      AuthenticatedClassroomsIdStudentsNewRoute,
  }

const AuthenticatedClassroomsRouteWithChildren =
  AuthenticatedClassroomsRoute._addFileChildren(
    AuthenticatedClassroomsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClassroomsRoute: typeof AuthenticatedClassroomsRouteWithChildren
  AuthenticatedCollegesRoute: typeof AuthenticatedCollegesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClassroomsRoute: AuthenticatedClassroomsRouteWithChildren,
  AuthenticatedCollegesRoute: AuthenticatedCollegesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  StudentsRollRoute: StudentsRollRoute,
  ApiPublicCronRefreshRoute: ApiPublicCronRefreshRoute,
  ApiPublicCronSeedDemoRoute: ApiPublicCronSeedDemoRoute,
  ApiPublicJobsPumpRoute: ApiPublicJobsPumpRoute,
  ApiPublicJobsRunRoute: ApiPublicJobsRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
